/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.TAOPHIEUDHBUS;
import BUS.SACHBUS;
import DTO.TAOPHIEUDHDTO;
import DTO.SACHDTO;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MKZ
 */
public class TAOPHIEUDHGUI extends javax.swing.JFrame {

    /**
     * Creates new form TaoPhieuForm
     */
    TableRowSorter sorter;
    DefaultTableModel model;
    TAOPHIEUDHBUS chiTietPhieuBus ;
    public TAOPHIEUDHGUI() {
        initComponents();
        //closing program without closing main UI
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadSach();
        chiTietPhieuBus = new TAOPHIEUDHBUS();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jButton15 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo yêu cầu nhập sách"));

        jLabel12.setText("Tên sách");

        jTextField5.setEditable(false);
        jTextField5.setText("LỌ LEM");

        jButton15.setText("Sửa");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSoLuongEvent(evt);
            }
        });

        jLabel13.setText("Số lượng đặt");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton15))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Số lượng đặt", "id Sách", "Tác giả", "Số lượng", "NXB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setColumnSelectionAllowed(true);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                getSoLuongEvent(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton16.setText("Tạo phiếu đặt hàng");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuPhieuEvent(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Tác giả", "Số lượng", "NXB", "id Sách"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addSachEvent(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton19.setText("Xóa");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaSachListEvent(evt);
            }
        });

        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                timSachEvent(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton19)))
                .addGap(25, 25, 25))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16)
                            .addComponent(jButton19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void editSoLuongEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSoLuongEvent
       if(jTable3.getSelectedRow() != -1){
            jTable3.setValueAt((Integer)jSpinner2.getValue(), jTable3.getSelectedRow(), 1);
        }
    }//GEN-LAST:event_editSoLuongEvent

    private void xoaSachListEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaSachListEvent
        // TODO add your handling code here:
        if(jTable3.getSelectedRow()!=-1){
        
        ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{
            jTable3.getValueAt(jTable3.getSelectedRow(), 0)
           ,jTable3.getValueAt(jTable3.getSelectedRow(), 3)     
           ,jTable3.getValueAt(jTable3.getSelectedRow(), 4)     
           ,jTable3.getValueAt(jTable3.getSelectedRow(), 5)
           ,jTable3.getValueAt(jTable3.getSelectedRow(), 2)     
                
        });
        ((DefaultTableModel)jTable3.getModel()).removeRow(jTable3.getSelectedRow());
        }
    }//GEN-LAST:event_xoaSachListEvent

    private void luuPhieuEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuPhieuEvent
       
        // save phieu
        //tao phieu
        // tao chi tiet phieu
        ArrayList<TAOPHIEUDHDTO> arr = new ArrayList<>();
//        new CHITIETPHIEUDTO(WIDTH, HEIGHT, WIDTH, tenSach)
        for(int i =0;i< jTable3.getRowCount();i++){
            arr.add(new TAOPHIEUDHDTO(
                Integer.parseInt(jTable3.getValueAt(i, 2).toString())
                ,Integer.parseInt(jTable3.getValueAt(i, 1).toString())
//                ,Integer.parseInt(jTable3.getValueAt(i, 2).toString())
                ,jTable3.getValueAt(i, 0).toString()    
            ));
        System.out.println(arr.get(i).toString());
        }

        
                if(arr.size() > 0)
        chiTietPhieuBus.savePhieu(arr);
    }//GEN-LAST:event_luuPhieuEvent

    private void addSachEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSachEvent

       // TODO add your handling code here:
//        DefaultTableModel model = new DefaultTableModel();
        if(model == null){
            model = new DefaultTableModel();
        model.addColumn("Tên sách");
        model.addColumn("Số lượng đặt");
        model.addColumn("id Sách");
        model.addColumn("Tác giả");
        model.addColumn("Số lượng");
        model.addColumn("Nhà cung cấp");
        
        }
        
//        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim());
        String idSach = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String tenSach = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim();
        String tacGia = jTable1.getValueAt(jTable1.getSelectedRow(), 1)==null?"":jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim();
        String soLuong = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String nhaCungCap = jTable1.getValueAt(jTable1.getSelectedRow(), 3)==null?"":jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().trim();
//        if(tenSach!="id"){
//            SACHDTO mSach = new SACHDTO(Integer.parseInt(jTextField7.getText().isEmpty()?"0":jTextField7.getText()),soluong,giaBan,tenSach,"");
//            SACHBUS sachBus = new SACHBUS();
            //        sachBus.saveSach(mSach);
//            int soluong = Integer.parseInt(jSpinner2.getValue().toString());
            model.addRow(new Object[]{tenSach
                    ,1
//                    ,jTextField17.getText().isEmpty()?"1000":jTextField17.getText()
                    ,idSach
                    ,tacGia
                    ,soLuong
                    ,nhaCungCap
            });
//        }
        jTable3.setModel(model);
        ((DefaultTableModel)jTable1.getModel()).removeRow(jTable1.getSelectedRow());
        
        jTable3.getColumnModel().getColumn(2).setMaxWidth(0);
        jTable3.getColumnModel().getColumn(2).setMinWidth(0);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(0);
        jTable3.getColumnModel().getColumn(3).setMaxWidth(0);
        jTable3.getColumnModel().getColumn(3).setMinWidth(0);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(0);
        jTable3.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable3.getColumnModel().getColumn(4).setMinWidth(0);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(0);
        jTable3.getColumnModel().getColumn(5).setMaxWidth(0);
        jTable3.getColumnModel().getColumn(5).setMinWidth(0);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(0);
    }//GEN-LAST:event_addSachEvent

    private void timSachEvent(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timSachEvent
        // TODO add your handling code here:
        if(sorter != null)
            sorter.setRowFilter(RowFilter.regexFilter(jTextField18.getText().toUpperCase(), 0));
            

        
    }//GEN-LAST:event_timSachEvent

    private void getSoLuongEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getSoLuongEvent
       
        
        jTextField5.setText( jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());
        jSpinner2.setValue((Integer)jTable3.getValueAt(jTable3.getSelectedRow(), 1));
//        jTextField7.setText( jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString());
        
//        if(jTable3.getSelectedRow() != -1){
//            jTable3.setValueAt((Integer)jSpinner2.getValue(), jTable3.getSelectedRow(), 1);
//        }
        
        
    }//GEN-LAST:event_getSoLuongEvent
    private void loadSach() {
         SACHBUS sachBus = new SACHBUS();
        ArrayList<SACHDTO> arr = sachBus.getAll();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tên sách");
        model.addColumn("Tên tác giả");
        model.addColumn("Số lượng");
//        model.addColumn("Giá bán");
        model.addColumn("Nhà cung cấp");
        model.addColumn("id Sách");
//        model.addColumn("1");
          for(int i=0;i< arr.size();i++){
            model.addRow(new Object[]{
                     arr.get(i).getTenSach().trim()
                    ,arr.get(i).getTacGia().trim()
                    ,arr.get(i).getSoLuong()
//                    ,arr.get(i).getGiaBan()
                    ,arr.get(i).getNhaCungCap()
                    ,arr.get(i).getIdSach()
            });
         }
          jTable1.setModel(model);
          sorter = new TableRowSorter<>(jTable1.getModel());
          jTable1.setRowSorter(sorter);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TAOPHIEUDHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TAOPHIEUDHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TAOPHIEUDHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TAOPHIEUDHGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TAOPHIEUDHGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    

}
